Created SaumyaGupta_Profile.md
WomenWhoCode/WWCodeGreenville pull request #103
Opened 2023-10-26 16:09 UTC by ISaumya1011

Thank you so much for giving me this opportunity to contribute my profile. Being new to this community, I am still in the learning process. Please see if you can see my file. Thank you!

2023-10-27 15:45 UTC, ISaumya1011 commented
Hi mam, can you please tell me if this request can be merged. It's a really important contribution to me mam, kindly tell if I need to do something else for this to be merged. Thanking you!

2023-10-27 16:42 UTC, JenBauer requested changes
This is a great start to your portfolio!  The only other recommendation that I didn't include is that you mentioned a YouTube channel - it's up to you if you want to include that in your social media links.  It could be fun!  Otherwise, my only feedback related to the updates under the learning/upcoming section.

2023-10-27 16:42 UTC, JenBauer commented on 2023_Hacktoberfest/Profiles/SaumyaGupta_Profile.md
> +### Mentee at Google Developer Student Council (GDSC)
I would recommend adjusting these subheadings to be additional bullet points, or add additional text or context under the subheading so that the grouping is more clear for your audience.
```suggestion
* Mentee at Google Developer Student Council (GDSC)
```

2023-10-27 16:42 UTC, JenBauer commented on 2023_Hacktoberfest/Profiles/SaumyaGupta_Profile.md
> +### Waiting for the upcoming 7 days Cloud Workshop
I recommend adjust this subheading to be another bullet point, or adding text under the subheading.
```suggestion
* Waiting for the upcoming 7 days Cloud Workshop
```

2023-10-27 17:20 UTC, ISaumya1011 commented
> This is a great start to your portfolio! The only other recommendation that I didn't include is that you mentioned a YouTube channel - it's up to you if you want to include that in your social media links. It could be fun! Otherwise, my only feedback related to the updates under the learning/upcoming section.

Thank you mam! I'm thankful for your suggestions and have updated them. Please check them.

2023-10-27 18:17 UTC, klmansel commented
Thank you for the updates @ISaumya1011! We appreciate your contribution ✨

2023-10-27 18:17 UTC, klmansel approved these changes

2023-10-27 18:17 UTC, merged

2023-10-28 06:18 UTC, ISaumya1011 commented
> Thank you for the updates @ISaumya1011! We appreciate your contribution ✨

Thank you mam for merging my contribution. It was an amazing experience working with @JenBauer mam  and you.