Update Chapter4.md
WomenWhoCode/WWCodeGreenville pull request #105
Opened 2023-10-27 18:59 UTC by pksuperduper

New Chapter 4 by Prayrana Khadye

2023-10-27 19:01 UTC, pksuperduper commented
@JenBauer -- I put Chapter 8 and Chapter 9 to fit in with what was not taken.  Let me know how to change that.  I also chose the prime request to start with since it was fun!

2023-10-28 14:01 UTC, JenBauer requested changes
This is excellent, thank you for jumping in!

My only comment here is to adjust the choices at the end to reflect actions instead of thoughts, which helps the reader have clarity on what they are choosing, and gives the next author a clear direction and prompt for what to start with in the next chapter.

2023-10-28 14:01 UTC, JenBauer commented on 2023_Hacktoberfest/InteractiveFiction-API_Antics/Chapter4.md
> +- If Sam wonders why she sees an immediate response, gets scared that no one is there, and wonders what to do next, turn to [Chapter 9](Chapter9.md).
For this section, could this be updated to reflect two actions that Sam can take, rather than two different thoughts she has?  In this type of story, the reader needs to make an actionable choice about the protaganist's next step at this point.

I think we could reword it this way to make the next action she takes clear.  It's just a suggestion - uou're welcome to adjust it however you like. :)

```suggestion
### What does Sam decide to do next?
- If Sam feels confident that she does not need the goblins and attempts to make a request that bypasses them altogether, turn to [Chapter 8](Chapter8.md).
- If Sam is spooked by the quick responses and decides to leave early for the day, turn to [Chapter 9](Chapter9.md).
```

2023-10-29 17:55 UTC, klmansel approved these changes
I think this addresses the PR comments, but I will defer to Jen for final approval

2023-10-30 00:39 UTC, JenBauer approved these changes
All good, let's keep this rolling!

2023-10-30 00:39 UTC, merged