Event page
WomenWhoCode/WWCodeGreenville pull request #122
Opened 2023-10-30 19:53 UTC by kodebae

## Adding An Event Video Page to Docs
* The purpose of this PR is to add a file where we can link back to WWCode Greenville online events.
* The suggested change solves the issue of not having a file for this before.
* I am requesting the following feedback from @klmansel 

### Type of Change
Added a Markdown file with links to YT content.

### How Has This Been Tested?
Manually tested each link.

2023-10-30 21:02 UTC, klmansel commented
@kodebae can you resolve the merge conflicts? Maybe your `main` branch was behind?

2023-10-30 21:39 UTC, klmansel requested changes

2023-10-30 21:39 UTC, klmansel commented on README.md
> +  * [PR Template](#pr-template)
is this from another PR?

2023-10-30 21:39 UTC, klmansel commented on README.md
> +-->
This is the PR template - I see that now. Did you mix 2 issues maybe?

2023-10-30 21:39 UTC, klmansel commented on WWCode_Event_Recordings/EventRecordings.md
> +*You can find a list of all of WWCodes videos [here](https://www.youtube.com/@WomenWhoCode/) on our YouTube channel. Don't forget to subscribe for future updates.*
our network YouTube url is https://www.youtube.com/playlist?list=PLVcEZG2JPVhclL1RUkH6Dt0nE3CXFcXpj

2023-10-30 21:39 UTC, klmansel commented on WWCode_Event_Recordings/EventRecordings.md
> +*You can find a list of all of WWCodes videos [here](https://www.youtube.com/@WomenWhoCode/) on our YouTube channel. Don't forget to subscribe for future updates.*
There are a few more videos there

2023-10-30 21:42 UTC, kodebae commented on README.md
> +  * [PR Template](#pr-template)
Yes I had already added code for this when I created the PR.

2023-10-30 22:04 UTC, kodebae commented on README.md
> +  * [PR Template](#pr-template)
Not sure what happened I think I added code before I switched to a new branch. Sorry about that.

2023-10-30 23:03 UTC, klmansel requested changes
almost! can you remove the code that doesn't belong to this PR?

2023-10-30 23:03 UTC, klmansel commented on README.md
> +  * [PR Template](#pr-template)
@kodebae can you remove this code from this branch?

2023-10-30 23:03 UTC, klmansel commented on README.md
> +-->
@kodebae can you remove this from this branch too?

2023-10-30 23:04 UTC, klmansel commented on WWCode_Event_Recordings/EventRecordings.md
> +*You can find a list of all of WWCodes videos [here](https://www.youtube.com/@WomenWhoCode/) on our YouTube channel. Don't forget to subscribe for future updates.*
```suggestion
*You can find a list of all of WWCode videos [here](https://www.youtube.com/playlist?list=PLVcEZG2JPVhclL1RUkH6Dt0nE3CXFcXpj) on our YouTube channel. Don't forget to subscribe for future updates.*
```

2023-10-30 23:04 UTC, kodebae commented on WWCode_Event_Recordings/EventRecordings.md
> +*You can find a list of all of WWCodes videos [here](https://www.youtube.com/@WomenWhoCode/) on our YouTube channel. Don't forget to subscribe for future updates.*
I checked the link. I belive I linked to these videos already. But thank you for letting me know.

2023-10-30 23:09 UTC, kodebae commented on README.md
> +-->
Yes, I am taking this out now. I was not aware that we needed to add this directly into GH. I thought that I was supposed to add the markdown directly to the README.md. I apologize for the confusion on my part.

2023-10-30 23:14 UTC, klmansel requested changes

2023-10-30 23:14 UTC, klmansel commented on .DS_Store
Please remove this file as well. You can actually add it to `.gitignore` so this won't be an issue in every PR (not just yours)

2023-10-30 23:15 UTC, kodebae commented on README.md
> +  * [PR Template](#pr-template)
done. ;)

2023-10-30 23:23 UTC, klmansel commented on README.md
> +  * [PR Template](#pr-template)
The Readme still has the PR template stuff in it 🤔

2023-10-31 00:59 UTC, closed without merging

2023-10-31 01:33 UTC, kodebae commented on .DS_Store
It seems like this has been resolved on my end somehow. I am seeing .DS_store in my .gitignore right now.

2023-10-31 01:35 UTC, klmansel commented on .DS_Store
Cool! Your other PR has been merged - once you open a new PR we can get this one in!

2023-10-31 01:35 UTC, klmansel commented on .DS_Store
(Or reopen this one)