Add test to make sure status is a known value to us.
WomenWhoCode/WWCodeGreenville pull request #134
Opened 2023-11-02 17:05 UTC by pksuperduper

# Pull Request

## Description
Add test to make sure status is a known value to us.  Inspired from (https://github.com/hackgvl/events-api/issues/83).

## Motivation
Eventbrite and meetup statuses are not always known to our python code.  So, added a test to make sure that if there is an unknown status to our python code, we catch it earlier.

## Testing Procedures
Tested in Postman.  I will apply the change on the postman code too.

## Checklist
- [ ] Code adheres to project coding standards.
- [ ] Tests cover the added or modified code.
- [ ] Documentation has been updated, if necessary.
- [ ] All new and existing tests pass successfully.
- [ ] The pull request is up to date with the latest changes from the main branch.

## Reviewer Guidelines
[Provide guidance for reviewers. Describe specific aspects they should focus on during the review and any special testing or use cases they should consider.]

## Screenshots or Visuals
[Include any relevant screenshots, diagrams, or visual aids to help reviewers understand the changes visually.]

## Additional Information
[Add any other pertinent details, such as links to related issues or documentation.]

Fixes #[94]

2023-11-03 01:36 UTC, JenBauer commented
Hey @pksuperduper, can you test that this works by running the Github Action for the test suite on your fork?  I'm not entirely sure if it's possible, I'm just wondering if we could do so as part of these reviews going forward.  I know I can run an action for a branch from the main repository, but I'm not sure if it's possible from the forked repository.

2023-11-03 14:51 UTC, pksuperduper commented
I tested this code in Postman since I do not think you can test any code on GitHub only.  I thought you have to use an editor or tool of your choice (like Eclipse, Postman, or command line tool).  Also, the JSON I am updating here looks like it is just an export of the Postman code and formatted for visual purposes.  So, I tested in Postman directly on my account to make sure it works.  You can correct me if I am wrong.  Also, I posted a screenshot in the commit comment.

> Hey @pksuperduper, can you test that this works by running the Github Action for the test suite on your fork? I'm not entirely sure if it's possible, I'm just wondering if we could do so as part of these reviews going forward. I know I can run an action for a branch from the main repository, but I'm not sure if it's possible from the forked repository in this case.

2023-11-04 13:32 UTC, JenBauer commented
Hey @pksuperduper, both of the PRs previously failed when run as Github Actions, so that's what clued me in that I wasn't checking for the JSON formatting close enough.  Since the end result is the successful run of the test suite as a Github Action, I'm thinking this process needs a revision.

For this review, I took your PR file and attempted to import it into my local Postman workspace, and it would not import.  This clued me in to a possible JSON formatting issue.
I then used [https://jsonlint.com/] to do a quick JSON file format check, and an initial parse error comes up on Line 41.

Let's try a different process for this update instead.
1. In the WWCode Postman Workspace, you should now have Edit permissions, but please let me know if you do not.  [In the Tests tab for the Events API request](https://www.postman.com/jen-bauer/workspace/wwcode-gvl-api-training/request/14924326-9af4adb4-b484-496e-b08c-fdc25f2864d7), try adding in your assertion update just as you did in your own local space.
2 Export the Collection file, and update this PR with the new file.  This should export as fully formed JSON file straight from Postman.  I think that will clear the first hurdle of ensuring that the file comes out exactly as intended.

For the Github Action, I don't see this action set up in your fork where I thought it might be [here](https://github.com/pksuperduper/WWCodeGreenville/actions) but I do know that I can run it from a branch from the main repository like this: 
![image](https://github.com/WomenWhoCode/WWCodeGreenville/assets/43556044/5cd1594e-1e3f-4487-939b-7ae554b5ce50)
Would it be possible for you to make a branch for the next PR change like this?  That way, I also can try running your change as an action as a test as part of the review process.  I'm also wondering if I could give you permissions to run your own branch for that action, but I'm not sure how to set that up yet.  At least if we could verify that way, we'd know for sure everything works before merging into the main branch.

2023-11-04 13:34 UTC, JenBauer requested changes

2023-11-04 13:34 UTC, JenBauer commented on HackGreenvilleEventsAPITestSuite/EventsAPI.json
> +							"    for (let i=0; i <responseData.length; i++) {",
```suggestion
							"    \tfor (let i=0; i <responseData.length; i++) {",
```
This is where the import fails, likely because there is character escaping that is missing.  The previous lines show this in effect from where it was repaired earlier from a fresh file import that I put in the repository.

2023-11-04 14:26 UTC, pksuperduper commented
That process sounds great.  Now that I have admin access to Postman workspace, I exported from there.  We can add a checklist item with details or document somewhere how to make changes to this API file!  Great idea!

2023-11-04 15:44 UTC, pksuperduper commented on HackGreenvilleEventsAPITestSuite/EventsAPI.json
> +							"    for (let i=0; i <responseData.length; i++) {",
I exported the JSON from Postman and committed a new change on this PR/

2023-11-07 14:23 UTC, JenBauer requested changes
Hi @pksuperduper, this is still an invalid JSON file for me when I update my local copy of your PR and check for validity.  The entire file needs to be overwritten with the new exported JSON file.

Can you check the following and do another export?  We'll see if we can shake out what the trouble is:
- The export is at the Collection level for "HackGreenville Events API Test Suite" with your changes included
- The export is a Collection v2.1 file when prompted to export from Postman
- The entire file is pasted into this directory and uploaded into the pull request 

I have a fresh attachment of an export I made this morning for comparison, in case it helps: [EventsAPI.json](https://github.com/WomenWhoCode/WWCodeGreenville/files/13281436/EventsAPI.json)

2023-11-07 19:48 UTC, JenBauer commented
I just checked this out again, and this appears to be working as expected now and the JSON is valid.  This is good to go, so I am accepting it and merging it in.

2023-11-07 19:48 UTC, JenBauer approved these changes

2023-11-07 19:49 UTC, merged