Added links for Online WWCode Greenville presence.
WomenWhoCode/WWCodeGreenville pull request #60
Opened 2023-10-21 12:53 UTC by prakartigoel24

Please add "hacktoberfest" and "hacktoberfest-accepted" Label to my PR.
This PR fixes issue #59.

 - Added a Find us online section to show all the links .
 - Added links for Meetup
 - Facebook
 - X (Twitter)
 - WWCode Greenville Website
 - Open Collective website 

# Check image here : 
 

![image](https://github.com/WomenWhoCode/WWCodeGreenville/assets/65300982/e06ac1ee-cdfd-41e3-97cc-fedd1450f01f)

2023-10-21 20:06 UTC, JenBauer requested changes

2023-10-21 20:06 UTC, JenBauer commented on README.md
> +## Find us online
Can this be changed to "Find Us Online" (proper case)?  Thanks!

2023-10-21 20:06 UTC, JenBauer commented on README.md
> +## Find us online
Also, can two more sites be added in here: the Instagram account and Notion account links from this Link Tree page? https://linktr.ee/wwcodegville

2023-10-22 18:42 UTC, prakartigoel24 commented on README.md
> +## Find us online
Sure, making these changes asap.

2023-10-22 18:55 UTC, prakartigoel24 commented
@JenBauer I have updated the Readme.md with the proposed changes.
Also, please add 'hacktoberfest-accepted' label to my PR. Thank you so much!

2023-10-22 18:59 UTC, JenBauer approved these changes
Thank you for the updates.  Approved.

2023-10-22 18:59 UTC, merged