add Getting Starting file
WomenWhoCode/WWCodeGreenville pull request #96
Opened 2023-10-24 04:18 UTC by git-create-devben

I add a file name GettingStarting.md where I simplify how to contribute with details step and add some image to show how to contribute and I remove how to contribute from README.md to GettingStarted.md, In the readme file on how to contribute I link it to GettingStarting files.

Am open for any corrections.

2023-10-24 12:28 UTC, klmansel requested changes
A few small changes in the Readme, and I love the creativity of your profile! 
Can you move that to a separate PR that closes #68 ? Thanks for your contributions!

2023-10-24 12:28 UTC, klmansel commented on Gettingstarted.md
> +`https://github.com/<Your_username>/WWCodeGreenville.git`
```suggestion
`https://github.com/<your_username>/WWCodeGreenville.git`
```

2023-10-24 12:28 UTC, klmansel commented on Gettingstarted.md
> +**Clone this repository** to your local manchine. Open a termianl navigate to the directory where you want to clone this repository. Then, run the following command:
```suggestion
**Clone this repository** to your local machine. Open a terminal and navigate to the directory where you want to clone this repository. Then, run the following command:
```

2023-10-24 12:28 UTC, klmansel commented on Gettingstarted.md
> +Replace <your_username> with your GitHub username
```suggestion
Replace `<your_username>` with your GitHub username
```

2023-10-24 12:28 UTC, klmansel commented on Gettingstarted.md
> +Replace <branch_name> with the name of the branch that you want to create.
```suggestion
Replace `<branch_name>` with the name of the branch that you want to create.
```

2023-10-24 12:28 UTC, klmansel commented on Gettingstarted.md
> +Replace <commit_message> with a short message that describes your changes.
```suggestion
Replace `<commit_message>` with a short message that describes your changes.
```

2023-10-24 12:28 UTC, klmansel commented on Gettingstarted.md
> +Replace <branch_name> with the name of the branch that you want to pushed your changes to.
```suggestion
Replace `<branch_name>` with the name of the branch that you want to pushed your changes to.
```

2023-10-24 12:28 UTC, klmansel commented on Gettingstarted.md
> +7.**Create a pull request**. Go to the repository page that you forked and click the **Compare and pull request**.
```suggestion
7.**Create a pull request**. Go to the repository page that you forked and click the **Compare and pull request** button
```

2023-10-24 12:28 UTC, klmansel commented on Gettingstarted.md
> +8.**Respond to feedback**. we may review your changes and suggest improvements. so try to Respond to our feedback and make any necessary changes.
```suggestion
8.**Respond to feedback**. We may review your changes and suggest improvements, so try to respond to our feedback and make any necessary changes.
```

2023-10-24 12:28 UTC, klmansel commented on Gettingstarted.md
> +9.**Merge your pull request**. Once we're happy with your changes, they we will merge your pull request into the main branch of the repository.
```suggestion
9.**Merge your pull request**. Once we're happy with your changes, we will merge your pull request into the main branch of the repository.
```

2023-10-24 12:28 UTC, klmansel commented on README.md
> +## Getting started
@git-create-devben Let's leave the Hacktoberfest section in and add the Getting Started section, but with a heading that matches the others and a link from the Table of Contents. We'll remove the Hacktoberfest section after this month.

2023-10-24 13:21 UTC, git-create-devben commented on README.md
> +## Getting started
Thanks for your suggestions, can you please clarify what you by "link from the Table of Contents"

2023-10-24 13:30 UTC, git-create-devben commented on README.md
> +## Getting started
Thanks for the suggestions, I can see the installation and prerequisites are sub list under the hacktoberfest2023 so am adding Getting Started section after prerequisite. is that okey or I should just leave it the way it's above the installation.

2023-10-24 19:41 UTC, klmansel requested changes
One small change and I'll get this approved and merged - thanks!

2023-10-24 19:41 UTC, klmansel commented on README.md
> +To learn how to contribute to this project, please see the [getting started guide](./GettingStarted.md).
@git-create-devben can you add a newline after the heading here so the description can be on the next line?

2023-10-25 12:28 UTC, JenBauer commented
I think the fix in the other PR was meant to go with this one?

2023-10-26 13:14 UTC, git-create-devben commented
She didn't merge this one so she merge the second branch and I push the changes to the second branch. is it showing some kind of error or conflict ?

2023-10-27 18:22 UTC, klmansel commented
@git-create-devben sorry about that! can you reopen the 404 PR and I'll accept that one! Thank you ⭐️

2023-10-27 18:22 UTC, closed without merging